### PR TITLE
Attempt to fix the build.

### PR DESCRIPTION
**Pull request by Happy0**

### CODE REVIEW

**Comment by atoulme** [comment]
Added you to whitelisted users to run builds

**Comment by Happy0** [comment]
Thanks a lot :)

**Comment by Happy0** [comment]
@atoulme - I fixed the warnings regarding the `split` method, but the build seems to be failing for another reason:

```
Recording test results
ERROR: Step ?Publish JUnit test result report? failed: Test reports were found but none of them are new. Did leafNodes run? 
For example, /home/jenkins/jenkins-slave/workspace/Apache Tuweni/CI/bytes/build/test-results/test/TEST-org.apache.tuweni.bytes.BufferBytesTest.xml is 11 days old
```

**Comment by atoulme** [comment]
It seems like the CI machines are hung up at the moment: `Caused by: java.lang.OutOfMemoryError: unable to create new native thread`

CI machines are shared and may be under heavy load. Best bet is to retry.

**Comment by Happy0** [comment]
Merging this for now since Jenkins seems to be building an older commit when I try to rebuild / push to this PR.

**Pull request merged**
