### PR TITLE
Add dockerfile + readme directions

### PR DESCRIPTION
**Pull request by Leibniz137**
I hope this makes it a little easier for some people to get started

lmk

nate

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by atoulme** [comment]
Thanks for the contrib! We have a Dockerfile for relayer here: https://github.com/apache/incubator-tuweni/blob/master/dist/docker/relayer.Dockerfile

**Comment by Leibniz137** [comment]
ah, ok I missed that. This was part of my first steps of figuring out how to make a test harness for hobbits for this bounty: https://github.com/PegaSysEng/BountiedWork/issues/7

I could do a couple things:

1. Adapt the new README directions to reference the existing dockerfile
2. Update the existing dockerfile to use a [multistage build](https://docs.docker.com/develop/develop-images/multistage-build/). The benefit would be to remove the strict gradle build dependency by using gradle inside the first docker build container
3. Just close this PR, no changes

let me know which option(s) make sense

**Comment by atoulme** [comment]
1. sounds good!

**Pull request closed without merging**
